;/*FB_PKG_DELIM*/

__d("CometHeroLogging",["hero-tracing"],(function(t,n,r,o,a,i,l){"use strict";l.default=o("hero-tracing").HeroLogger}),98);
__d("CometInteractionTracingQPLConfigContext",["qpl","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useContext,d=u.useMemo,m={dialogTraceQPLEvent:r("qpl")._(30605361,"6204"),popoverTraceQPLEvent:r("qpl")._(30605361,"6204")},p=s.createContext(m);function _(){return c(p).dialogTraceQPLEvent}function f(){return c(p).popoverTraceQPLEvent}function g(e){var t=o("react-compiler-runtime").c(6),n=e.children,r=e.dialogTraceQPLEvent,a=e.popoverTraceQPLEvent,i;t[0]!==r||t[1]!==a?(i={dialogTraceQPLEvent:r,popoverTraceQPLEvent:a},t[0]=r,t[1]=a,t[2]=i):i=t[2];var l=i,u;return t[3]!==n||t[4]!==l?(u=s.jsx(p.Provider,{value:l,children:n}),t[3]=n,t[4]=l,t[5]=u):u=t[5],u}l.defaultInteractionQPLEvents=m,l.useDialogTraceQPLEvent=_,l.usePopoverTraceQPLEvent=f,l.CometInteractionTracingQPLConfigContextProvider=g}),98);
__d("CometOverlayCloseHandlerContext",["react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useContext,d=u.useEffect,m=s.createContext(null);function p(e){var t=o("react-compiler-runtime").c(4),n=c(m),r,a;t[0]!==e||t[1]!==n?(r=function(){if(!(n==null||e==null)){var t=n(e);return t}},a=[n,e],t[0]=e,t[1]=n,t[2]=r,t[3]=a):(r=t[2],a=t[3]),d(r,a)}l.CometOverlayCloseHandlerContext=m,l.useCometOverlayCloseHandler=p}),98);
__d("ErrorBoundaryForLazyLoad",["cr:38535","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));l.default=n("cr:38535")}),98);
__d("IntlCLDRNumberType02",["IntlVariations"],(function(t,n,r,o,a,i,l){"use strict";var e={getVariation:function(t){return t===0||t===1?r("IntlVariations").NUMBER_ONE:r("IntlVariations").NUMBER_OTHER}},s=e;l.default=s}),98);
__d("IntlCLDRNumberType03",["IntlVariations"],(function(t,n,r,o,a,i,l){"use strict";var e={getVariation:function(t){return t===0||t===1?r("IntlVariations").NUMBER_ONE:r("IntlVariations").NUMBER_OTHER}},s=e;l.default=s}),98);
__d("IntlCLDRNumberType10",["IntlVariations"],(function(t,n,r,o,a,i,l){"use strict";var e={getVariation:function(t){return t===1?r("IntlVariations").NUMBER_ONE:r("IntlVariations").NUMBER_OTHER}},s=e;l.default=s}),98);
__d("IntlCLDRNumberType19",["IntlVariations"],(function(t,n,r,o,a,i,l){"use strict";var e={getVariation:function(t){return t===1?r("IntlVariations").NUMBER_ONE:t===0||t!==1&&t%100>=1&&t%100<=19?r("IntlVariations").NUMBER_FEW:r("IntlVariations").NUMBER_OTHER}},s=e;l.default=s}),98);
__d("IntlCLDRNumberType26",["IntlVariations"],(function(t,n,r,o,a,i,l){"use strict";var e={getVariation:function(t){return t===1?r("IntlVariations").NUMBER_ONE:t%10>=2&&t%10<=4&&(t%100<12||t%100>14)?r("IntlVariations").NUMBER_FEW:r("IntlVariations").NUMBER_MANY}},s=e;l.default=s}),98);
__d("JSResourceReference",["JSResourceReferenceImpl"],(function(t,n,r,o,a,i,l){l.default=r("JSResourceReferenceImpl")}),98);
__d("RtiRequestStreamQosFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("8530"),s=o("FalcoLoggerInternal").create("rti_request_stream_qos",e),u=s;l.default=u}),98);
__d("SidneeAbrConfigDefaults",[],(function(t,n,r,o,a,i){"use strict";var e=5e3,l="0,1,1; 80,1.5,1.3; 97,2.0,1",s=1,u=65,c=1,d=5e3,m=3e4,p=2,_="0,1,1.4; 100,2,1",f=1,g=3e4,h=1.7,y=80,C=1.3,b=1.5,v=1.85,S=50,R=.5,L=4,E="-1,2,1; 0,1.7,2; 1,1",k=1,I=4,T=2;i.avgSegmentDurationMsDefault=e,i.badUploadQualityRewardCurveDefault=l,i.badUploadQualityRewardCurveFallbackDefault=s,i.badUploadQualityThresholdDefault=u,i.bitrateMultiplierDefault=c,i.bufferReductionMsDefault=d,i.defaultVideoDurationMsDefault=m,i.encodingRiskDefault=p,i.goodUploadQualityRewardCurveDefault=_,i.goodUploadQualityRewardCurveFallbackDefault=f,i.lookAheadMsDefault=g,i.maxAggressiveRiskDefault=h,i.maxBandwidthConfidencePctDefault=y,i.maxConservativeRiskDefault=C,i.maxNormalRiskDefault=b,i.maxVeryAggressiveRiskDefault=v,i.minBandwidthConfidencePctDefault=S,i.minBitrateMultiplierDefault=R,i.rewardRatioRoundDigitsDefault=L,i.riskCurveDefault=E,i.riskCurveFallbackDefault=k,i.riskRatioRoundDigitsDefault=I,i.riskRewardRatioRoundDigitsDefault=T}),66);
__d("react-relay/relay-hooks/useMutationAction_EXPERIMENTAL",["Promise","react","react-compiler-runtime","react-relay/relay-hooks/useRelayEnvironment","relay-runtime"],(function(t,n,r,o,a,i){"use strict";var e,l,s=n("react-compiler-runtime").c,u=e||(e=n("react")),c=n("relay-runtime").commitMutation,d=u.useCallback;function m(e){var t=s(4),r=n("react-relay/relay-hooks/useRelayEnvironment")(),o,a;t[0]!==r||t[1]!==e?(o=function(o){return new(l||(l=n("Promise")))(function(t,n){c(r,{mutation:e,variables:o,onCompleted:function(n){t(n)},onError:function(t){n(t)}})})},a=[r,e],t[0]=r,t[1]=e,t[2]=o,t[3]=a):(o=t[2],a=t[3]);var i=d(o,a);return i}a.exports=m}),null);
__d("resolveImmediate",["Promise"],(function(t,n,r,o,a,i){var e,l=(e||(e=n("Promise"))).resolve();function s(e){l.then(e).catch(u)}function u(e){setTimeout(function(){throw e},0)}i.default=s}),66);
__d("tracePolicyFromResource",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){return e+"."+t.getModuleId()}i.default=e}),66);